num_trajectories: 8
trajectory_duration: 3.0
planning_timestep: 0.1
num_milestones: 5
num_interpolation_samples: 6
dynamic_obstacle_max_speed: 0.00 # m/s
dynamic_obstacle_duration: 5.0   # s
goal_tolerance: 0.03  # cost function tolerance

#itomp_algorithm: "fixed_trajectory_duration"
itomp_algorithm: "flexible_trajectory_duration"

static_obstacles:
  - {type: "sphere", position: [0.10,  0.05, 0.70], radius: 0.30}

#collision_sphere_links:
#  - shoulder_pan_link

cost_weights:
  #goal_pose: 1.0
  time: 1.0
  smoothness: 0.1
  collision: 3.0
  future_obstacle: 1.0
