trajectory_duration: 5.0
planning_timestep: 0.25
num_milestones: 5
num_interpolation_samples: 3
num_trajectories: 1

static_obstacles:
  - {file: "package://itomp_exec/env/table_collision.dae", position: [0.7, 0.0, 0.0]}

cost_weights:
  goal_pose: 1.0
  smoothness: 0.003
  collision: 1.0
  future_obstacle: 1.0
 
