trajectory_duration: 5.0
planning_timestep: 5.0
num_milestones: 3
num_interpolation_samples: 3

static_obstacles:
  - {file: "package://itomp_exec/env/table_collision.dae", position: [0.7, 0.0, 0.0]}

collision_sphere_links:
  - shoulder_pan_link
  - shoulder_lift_link
  - upperarm_roll_link
  - elbow_flex_link
  - forearm_roll_link
  - wrist_flex_link
  - wrist_roll_link
  - gripper_link
  - r_gripper_finger_link
  - l_gripper_finger_link

attatchable_objects:
  - {file: "package://itomp_exec/env/cylinder.dae"}
  - {file: "package://itomp_exec/env/cylinder.dae"}
  - {file: "package://itomp_exec/env/cylinder.dae"}
  - {file: "package://itomp_exec/env/cylinder.dae"}
  
cost_weights:
  goal_pose: 1.0
  smoothness: 0.01
  collision: 1.0
  future_obstacle: 1.0
 
