trajectory_duration: 3.0
num_milestones: 5
num_interpolation_samples: 5
num_trajectories: 1

static_obstacles:
  - {file: "package://itomp_exec/env/table.dae", position: [1.0, 0.0, 0.0]}

cost_weights:
  goal_pose: 1.0
  smoothness: 1.0
  collision: 1.0
