poses:
  - {type: "start",  position: [0.10,  0.60, 1.00], orientation: [0.707106781, 0.0, 0.707106781, 0.0]}
  - {type: "start",  position: [0.15,  0.60, 1.00], orientation: [0.707106781, 0.0, 0.707106781, 0.0]}
  - {type: "start",  position: [0.10,  0.65, 1.00], orientation: [0.707106781, 0.0, 0.707106781, 0.0]}
  - {type: "start",  position: [0.15,  0.65, 1.00], orientation: [0.707106781, 0.0, 0.707106781, 0.0]}
  - {type: "target", position: [0.60, -0.45, 0.90], orientation: [0.707106781, 0.0, 0.707106781, 0.0]}
  - {type: "target", position: [0.60, -0.15, 0.90], orientation: [0.707106781, 0.0, 0.707106781, 0.0]}
  - {type: "target", position: [0.60,  0.15, 0.90], orientation: [0.707106781, 0.0, 0.707106781, 0.0]}
  - {type: "target", position: [0.60,  0.45, 0.90], orientation: [0.707106781, 0.0, 0.707106781, 0.0]}

attachable_objects:
  - {type: "sphere", position: [0.70, -0.70, 0.35], radius: 0.063, attaching_link: "wrist_roll_link", attaching_position: [0.15, 0.0, 0.0]}
  - {type: "sphere", position: [0.70, -0.70, 0.35], radius: 0.063, attaching_link: "wrist_roll_link", attaching_position: [0.15, 0.0, 0.0]}
  - {type: "sphere", position: [0.70, -0.70, 0.35], radius: 0.063, attaching_link: "wrist_roll_link", attaching_position: [0.15, 0.0, 0.0]}
  - {type: "sphere", position: [0.70, -0.70, 0.35], radius: 0.063, attaching_link: "wrist_roll_link", attaching_position: [0.15, 0.0, 0.0]}

